import type { Metadata } from "next";

import AuthHeader from "@/components/auth/AuthHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuthHeader />
      <main className="flex min-h-[90dvh] flex-col justify-center items-center">
        {children}
      </main>
    </>
  );
}
